#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Christoph Sorger <christoph.sorger@gmail.com>

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# [CS] Virtualenv

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export PIP_REQUIRE_VIRTUALENV=true

