#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Christoph Sorger <christoph.sorger@gmail.com>

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# [CS] Virtualenv

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export PIP_REQUIRE_VIRTUALENV=true

# brew install cask java
export JAVA_HOME=$(/usr/libexec/java_home)

# We use macOS ruby, gem and bundle.
export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"
export GEM_HOME="$HOME/.gem/ruby/2.6.0"

# brew install go
export GOPATH=$HOME/.go
